### ISSUE TITLE
templates and readme.md completely messed up

### ISSUE THREAD

**Issue by rick-it-2004** [michaelklishin/neo4j-server-chef-cookbook#28]
Hi

You seem to have a bunch of HTML in the templates and readme.md. The repository is currently broken.

  Regards, Richard

**Comment by michaelklishin** [comment]
Can you be more specific than "completely broken"?

**Comment by michaelklishin** [comment]
I haven't found any HTML in the templates or [README.md](https://raw.githubusercontent.com/michaelklishin/neo4j-server-chef-cookbook/master/README.md).
